Add pressure
pxblue/icons pull request #107
Opened 2021-03-15 14:30 UTC by ericatha

#### Changes proposed in this Pull Request:
- Added icons for Pressure (Pressure and Pressure Alternate)
- Added icons for iOS Biometric Auth (Face ID and Touch ID)
- Added icons for companies/platforms for 3rd Party Login (Facebook, Google, Amazon, Apple)
- Added Amazon Alexa icon for 3rd party smart home ecosystem support

2021-03-15 19:39 UTC, huayunh commented
I don't get why we need the Apple touch id as part of the pxb icon page... I poked around the smart home project but didn't find where it is used.

If it is used more as an image instead of a 24x24 icon, then I'd suggest not including it here.

2021-03-16 13:30 UTC, ericatha commented
> I don't get why we need the Apple touch id as part of the pxb icon page... I poked around the smart home project but didn't find where it is used.
> 
> If it is used more as an image instead of a 24x24 icon, then I'd suggest not including it here.

This is used at the moment in Control Xpert Ag for biometric authentication setup and on the login screen when enabled. They are used as 24x24 icons within buttons, within avatars on settings, and as 96x96 on full page setup and success screens.

I'd expect that this would be one of the additions to the login patterns/components in pxblue as well @huayunh

2021-03-17 13:21 UTC, ericatha commented
@huayunh @joebochill Any movement on this? Are there changes I need to make? The GP dev team is bottlenecked right now waiting for the biometric icons.

2021-03-17 14:30 UTC, joebochill commented
Taking a look at it today

2021-03-17 14:40 UTC, joebochill commented
Material already has a facebook icon, is there a reason for making another one? https://pxblue.github.io/style/iconography?icon=Facebook&isMaterial=true

2021-03-17 15:03 UTC, joebochill requested changes
- There is an issue in the Meta file. During the rename to Apple Logo we ended up with two entries in the file (Apple and Apple Logo), and there is no apple_logo.svg file which is referenced by Apple Logo. This causes an error when building the MUI icon components package.
- Please update the version number in the package.json file (icons/package.json & icons/svg/package.json) to 1.2.0
- Please add a changelog entry in /CHANGELOG.md that lists out the newly added icons
- See comment above about the facebook icon

2021-03-17 17:48 UTC, huayunh commented
I will take care of the technical side; meanwhile, Eric you may just send them the SVG icons, and it will be fairly easy to swap those to PX Blue packages once the new icons get published

2021-03-18 22:02 UTC, huayunh commented
> They are used as 24x24 icons within buttons

That's not going to render well... I would not suggest doing that. It looks like this after you pixelate it: 
![image](https://user-images.githubusercontent.com/8997218/111703502-1a7c2880-8814-11eb-8e33-10220fc83b45.png)

2021-03-19 09:57 UTC, huayunh commented
In my commit above, both facebook logo and touch id are included, but I'd prefer to remove both, for the reasons mentioned above.

2021-03-19 12:05 UTC, joebochill commented on CHANGELOG.md
> +## v1.1.3 (not published yet)
I think we're moving to the habit of "new icons = minor version" to better align with semantic versioning. So this would be 1.2.0 instead.

2021-03-19 12:05 UTC, joebochill commented on package.json
> +    "version": "1.1.3",
```suggestion
    "version": "1.2.0",
```

2021-03-19 12:06 UTC, joebochill commented
Where did we end up on the discussion about the duplicate facebook icon and the low resolution of the touch id?

2021-03-22 13:30 UTC, ericatha commented
For the Facebook icon we could get either get rid of it _or_ rename to `facebook_circle`

2021-03-24 11:24 UTC, joebochill approved these changes

2021-03-24 11:27 UTC, joebochill commented
@huayunh once the automatic publishing finishes here, you'll need to open up another PR in the icons-mui repo (with an updated minor version in package.json and a changelog entry - you can copy the wording from this one)

2021-03-24 14:23 UTC, merged