Use brightlayer packages for MUI demo
pxblue/icons pull request #167
Opened 2021-11-15 15:30 UTC by joebochill

I had to do this to test something out, so figured I'd push it up.

#### Changes proposed in this Pull Request:
- Switch mui showcase to use brightlayer pacakges
- Update mui showcase to use grid to match layout of the icon-font demo file

#### To Test:
- yarn start

2021-11-15 16:42 UTC, emclaug2 commented on mui/demos/showcase/src/index.tsx
> +import * as PXBThemes from '@brightlayer-ui/react-themes';
import * as BLUIThemes from '@brightlayer-ui/react-themes';

2021-11-15 16:43 UTC, emclaug2 commented
Looks good otherwise!

2021-11-15 21:27 UTC, emclaug2 approved these changes

2021-11-16 08:09 UTC, bkarambe commented
@joebochill There is a pxblue reference in Changelog.md at line 47. 

- [ ] Remove pxblue reference in Changelog

2021-11-16 08:23 UTC, bkarambe commented
@joebochill Missed pxblue reference replacement in mui/Changelog.md at line 116.

2021-11-16 08:23 UTC, bkarambe commented
```tsx
// new import syntax
import IconName from '@pxblue/icons-mui/IconName';
```

- [ ] Please replace pxblue to brightlayer-ui in Changelog.md

2021-11-16 08:45 UTC, bkarambe commented
Please refactor Logo.tsx to remove px blue reference

- [ ] Remove pxb references from Logo.tsx

2021-11-16 08:46 UTC, bkarambe requested changes
Please address the feedback

2021-11-16 08:53 UTC, bkarambe commented
> I had to do this to test something out, so figured I'd push it up.
> 
> #### Changes proposed in this Pull Request:
> * Switch mui showcase to use brightlayer pacakges
> * Update mui showcase to use grid to match layout of the icon-font demo file
> 
> #### To Test:
> * yarn start

Please mention jira ticket number

2021-11-16 11:31 UTC, joebochill commented
Thanks for the feedback @bkarambe. Just to be clear, this PR is _not_ tied to a story. This is simply me fixing a bug with the demo so that it shows the correct icons. If there are other BLUI migration issues with the MUI demo, that story is currently assigned to you. If there are lingering issues with the BLUI migration for the icons packages (PXBLUE-2523, which was closed last sprint), then you can either address them as part of your story, or make a new issue in JIRA to come back and clean them up.

And for what it's worth...I don't think the Logo.tsx file is used at all in the demo (it can probably be removed). The mui changelog is fine because that line explicitly refers to the syntax for the old version of the package (the brightlayer scoped package does not exist at that version). And the /changelog file is pointing to a bug in our github org, which hasn't been renamed yet. @emclaug2 not sure if we'll want to handle all of these as a post-zero-day update (if so we should make sure that it's part of the AC for a story), or if we should update them ahead of time and let them be broken until zero day. Your call.

2021-11-16 12:50 UTC, bkarambe commented
@joebochill Thanks for the update. Approving PR everything goods.

2021-11-16 12:50 UTC, bkarambe approved these changes

2021-11-16 13:05 UTC, jeffvg commented
should updated sprites be checked in? I ran build:font and it includes sprites but didn't run. If you run sprites alone we have updated sprites

2021-11-16 15:09 UTC, emclaug2 commented
And the /changelog file is pointing to a bug in our github org, which hasn't been renamed yet. @emclaug2 not sure if we'll want to handle all of these as a post-zero-day update (if so we should make sure that it's part of the AC for a story), or if we should update them ahead of time and let them be broken until zero day. Your call.


I'd rather update the links now; @bkarambe could you take a look?

2021-11-17 08:02 UTC, bkarambe commented
@emclaug2 Sure. I will cover it as a part of PXBLUE-2609.

2021-11-17 13:54 UTC, merged